pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Compile') {
            steps {
                dir('jenkins-resources/calculator') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew compileJava'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('jenkins-resources/calculator') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew test'
                }
            }
        }
    }

    post {
        always {
            junit allowEmptyResults: true, testResults: 'jenkins-resources/calculator/build/test-results/test/*.xml'
        }
    }
}